[project]
name = "containcraft"
version = "0.1.0"
description = "YAML Builder CLI"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyfiglet>=0.8",
    "pyyaml>=6.0",
    "rich>=13.7",
]

[project.scripts]
contain = "containcraft.cli:main"
